### ISSUE TITLE
Errors in download_oasis_scans_bids.sh 

### ISSUE THREAD

**Issue by FL33TW00D** [NrgXnat/oasis-scripts#11]
Hi There,
I've been using this script on and off for the past year, and it's been a big help so thank you.

There are a few things that make the output not BIDS compliant though:
1. dataset_description.json - "BidsVersion" should be "BIDSVersion"
2. "sub-OAS30002_ses-d2345_echo-2_run-01_fieldmap.nii.gz" - The fieldmap download format is not BIDS compliant.
3. Fieldmap JSON sidecar should include an "IntendedFor" field.

Many thanks for the great script,
Chris

**Comment by sarahkeefe** [comment]
I looked into this - our standard conversion using dcm2niix v.2017-Oct-17 did not produce a magnitude nifti file with our fieldmaps, and we've provided all the data we have available. 

Both dcm2niix and the BIDS specification have definitely been updated since we released OASIS-3. I'm not sure if the BIDS validator can account for older BIDS versions - OASIS-3 uses the version of the BIDS spec that was available at the time, which was mainly 1.0.0, with updates made to incorporate 1.0.1 changes that were under discussion then. I'll make sure the upcoming releases we are working on are converted with an updated dcm2niix version and are compatible with the current BIDS spec, but we aren't able to make changes to the OASIS-3 dataset at this time.

Regarding the DTI: we don't have a single acquisition protocol to provide since the data released is from a number of different scanners and different protocols. All the details we have on them are provided in the JSON, bvec, and bval files. There isn't going to be a single uniform protocol for all our DTI data.

If you have more questions on the data itself, you can contact the project administrator at https://www.oasis-brains.org (the contact form there goes to the admins). I can also answer more detailed questions on the data conversion process through there.

I think I am going to close this issue since I think everything script-related has been covered. Feel free to re-open or open a new issue if you have more script questions, and I'll try to get to them quickly.

-Sarah

**Comment by FL33TW00D** [comment]
Hi @sarahkeefe,
Thanks for your detailed previous response. With some help I've worked out a working fieldmap scheme from the Siemens scanners that matches up with the current BIDS specification.

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data
From the above link the matching case is Case 1 (as is common with Siemens Scanners so a good clue we are on the right path).
 
From looking at the JSON sidecars for each of the files, it looks like the naming scheme should be as follows:
sub-OAS30002_ses-d2345_run-02_fieldmap.nii.gz --->  sub-OAS30002_ses-d2345_run-01_phasediff.nii.gz
sub-OAS30002_ses-d2345_echo-1_run-01_fieldmap.nii.gz ---> sub-OAS30002_ses-d2345_run-01_magnitude1.nii.gz
sub-OAS30002_ses-d2345_echo-2_run-01_fieldmap.nii.gz ---> sub-OAS30002_ses-d2345_run-01_magnitude2.nii.gz

The field in the JSON sidecars that tells us which is a magnitude and which is a phasedifference file is the ImageType entry (M for magnitude and P for phase). The only other thing that needs to be done to allow the fmap data to be used is the addition of the "EchoTime1" and "EchoTime2" fields to the Phase Difference file, corresponding to the echo times of the magnitude 1 & 2 files respectively (with the longer time being 2).

I hope this helps you in future releases. I also have a number of helpful python scripts for working with OASIS data that I could clean up and add to the repository (ie Clinical Data Matching, JSON changes etc). Let me know if this would be of interest to you as a thank you for your help.

Many Thanks,
Christopher Fleetwood

**Comment by sarahkeefe** [comment]
Wow, this is fantastic, thank you so much! I've passed this along to the team and we are going to aim to incorporate fieldmap naming changes into the currently-in-progress OASIS 4 as well as our upcoming additions to OASIS 3 (which may cause scripting to become confusing, but we'll see). 

Additions to this repository would be welcome! I have a very minimal "session_matchup" folder that currently has one simple R script in it but if you have any good additions for that, that would be super helpful. You can either make a pull request, or if you prefer you can send them to me directly and I can clean them up and post them (I checked and I think I have your email address from an OASIS contact form and I can respond to you via email there).

Thanks again so so much, this is great!

**Comment by dhivyasrin** [comment]
Hi @sarahkeefe and Christopher,

  I found this thread to be very helpful. I was trying to convert OASIS-3 BIDS to be compliant with new version of BIDS/BIDS validator and eventually run fMRIPrep. All the steps that you mentioned here were helpful in getting the fieldmap json sidecars ready. However,  I see there are few subjects with multiband resting state acquisition. Could you confirm if they are multiband acquisitions? If they are, I am getting few errors saying,

**Location:
BIDS_n/sub-OAS31409/ses-d0042/func/sub-OAS31409_ses-d0042_task-restingstateMB4_run-01_bold.json

Reason:
Invalid JSON file. The file is not formatted according the schema.

Evidence:
.SliceTiming[1] should be >= 0**

Location:
BIDS_n/sub-OAS31409/ses-d0042/func/sub-OAS31409_ses-d0042_task-restingstateMB4_run-01_bold.nii.gz

Reason:
"SliceTiming" value/s contains invalid value as it is greater than RepetitionTime. SliceTiming values should be in seconds not milliseconds (common mistake).

Evidence:
1.575

And also is there a way to get multiband acceleration factor?


<img width="648" alt="Screen Shot 2023-08-17 at 10 46 04 AM" src="https://github.com/NrgXnat/oasis-scripts/assets/37376696/bae3ce64-dfd0-4643-98d7-9013e9e239b2">
