### ISSUE TITLE
download_oasis_scans_wget.sh— .id not find a T1w,bold,fieldmap,dwi scan

### ISSUE THREAD

**Issue by GerardYu** [NrgXnat/oasis-scripts#17]
i'm not able to download any files at all. 

bash oasis-scripts-master/download_scans/download_oasis_scans_wget.sh list.csv ./ gerardyu T1w,bold,fieldmap,dwi

oasis-scripts-master/download_scans/download_oasis_scans_wget.sh: line 49: functions.sh: No such file or directory
Enter your password for accessing OASIS data on XNAT Central:
.hecking for a T1w,bold,fieldmap,dwi scan for OAS30374_MR_d0084
--2021-11-08 14:16:55--  https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30374/experiments/OAS30374_MR_d0084%0D/scans/T1w,bold,fieldmap,dwi/files?format=tar.gz
Resolving central.xnat.org (central.xnat.org)... 128.252.217.126
Connecting to central.xnat.org (central.xnat.org)|128.252.217.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-08 14:17:02 ERROR 404: Not Found.

.id not find a T1w,bold,fieldmap,dwi scan for OAS30374_MR_d0084
.one with OAS30374_MR_d0084
.hecking for a T1w,bold,fieldmap,dwi scan for OAS31006_MR_d0120
--2021-11-08 14:17:02--  https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS31006/experiments/OAS31006_MR_d0120%0D/scans/T1w,bold,fieldmap,dwi/files?format=tar.gz
Resolving central.xnat.org (central.xnat.org)... 128.252.217.126
Connecting to central.xnat.org (central.xnat.org)|128.252.217.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-08 14:17:09 ERROR 404: Not Found.

.. this repeats for every subject in the list.csv

here's the list.csv file [list.csv](https://github.com/NrgXnat/oasis-scripts/files/7494703/list.csv)

**Comment by sarahkeefe** [comment]
Hi, It looks like you didn't convert your list.csv file to Unix format. This is adding a %0D character to the experiment label in the URL so XNAT Central can't find anything that matches it. That's also what's causing the unusual formatting in your output (like the dots before each line). Follow the instructions I provide in the README [here](https://github.com/NrgXnat/oasis-scripts#note-on-unix-file-formatting) and retry and let me know how it goes.

404 errors like that can also be caused by typing your XNAT Central password incorrectly so you'll want to make sure that is correct as well. If you still see 404s after converting your CSV file to Unix format, and your output looks normal otherwise, make absolutely sure you can log in to https://central.xnat.org with the username and password you are entering when running the script.

**Comment by sarahkeefe** [comment]
Hi, I haven't heard back on whether you re-tried this so I am going to close this issue. Feel free to re-open or contact me if you have further issues.
