### ISSUE TITLE
download_oasis_scans.sh error in downloading

### ISSUE THREAD

**Issue by jainspoornima** [NrgXnat/oasis-scripts#18]
I am using this command to download data in Google Colab using the attached CSV, but getting the following errors in all files 

`!bash download_oasis_scans.sh OASIS_list.csv Data myusername T1w`
[OASIS_list.csv](https://github.com/NrgXnat/oasis-scripts/files/7635713/OASIS_list.csv)

```
Checking for a T1w scan for OAS30840_MR_d0042,  .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: .zip
Did not find a T1w scan for OAS30840_MR_d0042,  .
rm: cannot remove 'Data/OAS30840_MR_d0042,': No such file or directory
rm: cannot remove '.zip': No such file or directory
Done with OAS30840_MR_d0042,  .

Checking for a T1w scan for OAS31009_MR_d3330.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0curl: (7) Failed to connect to central.xnat.org port 443: Connection timed out
Did not find a T1w scan for OAS31009_MR_d3330.
rm: cannot remove 'Data/OAS31009_MR_d3330.zip': No such file or directory
Done with OAS31009_MR_d3330.
```

**Comment by sarahkeefe** [comment]
Hi,
Your file is incorrectly formatted. Opening your CSV file in a text editor shows this:

>OAS30154_MR_d0244,  
OAS30329_MR_d0376,  
OAS30502_MR_d0395,  
OAS30683_MR_d0528,"	"
OAS30840_MR_d0042,  
OAS31009_MR_d3330,
OAS30001_MR_d0129,"	    "
OAS30155_MR_d0785,  
OAS30330_MR_d0000,  
OAS30502_MR_d1195,  
OAS30683_MR_d1337,"	"
OAS30841_MR_d0187,  
OAS31009_MR_d3611,
OAS30001_MR_d0757,"	    "
OAS30156_MR_d0000, 


When you open a correct .csv file in a text editor like Notepad or Sublime Text you should see only one column that looks similar to the example .csv files provided in the oasis-scripts Github repository. I have an example .csv file in the script folder [here](https://github.com/NrgXnat/oasis-scripts/blob/79f70fc07f54a74c5afdf8c982e2b8af751e40b4/download_scans/oasis_scan_download_example.csv). There should be no commas or quotes at the end of each line - each line should contain only one MR session label for the session you want to download, like this:

>OAS30154_MR_d0244
OAS30329_MR_d0376
OAS30502_MR_d0395
OAS30683_MR_d0528

You should correct your CSV file and then open it in a text editor to be sure it is correctly formatted.
Once you have a list in the correct format, you will also need to convert your csv file from Windows format to Unix format before the script will work using the instructions in the README.

I am going to close this issue since it is an input issue rather than a script issue. Feel free to contact me if you have further questions about file formatting that the README does not cover.

**Comment by sarahkeefe** [comment]
I have one more note that is relevant to today only (December 1 2021) - we are experiencing a system outage that affects XNAT Central (where the OASIS data is stored) so downloads are unlikely to work today even with a correctly formatted file. If you experience further issues once you retry with a correctly formatted file, you may need to wait until tomorrow to re-attempt the download.
