### ISSUE TITLE
#10 should I processed .csv files downloaded without github and scripts?

### ISSUE THREAD

**Issue by gulyarauff** [NrgXnat/oasis-scripts#22]
Hi 
I have downloaded 5 csv files on OASIS 3: Subject, mr sessions, Clinical data, PEP and PUPs without running script from github.
Could I now start to use these csv files?
If not, what is the following step?
Is it possible to merge these file in one big file?
There few information related to the same subject, is it possible to filter by Subject. I mean to merge rows related to the same Subject? I understand is it not valid on all csv file .

**Comment by sarahkeefe** [comment]
Hi, There are separate instructions to follow depending on what exactly you need to do. If you are trying to download multiple different file types (e.g. PUP output, Freesurfer output, or scans) then you'll need to have a separate CSV file for each type that specifies which imaging sessions, or PUP outputs, or Freesurfer outputs that you want to download data for. For each file type you want to download, you'll need to make sure your input file matches the examples provided. There are separate scripts for each file type so you'll need to use the appropriate script. You should follow the instructions that are on the main README page (also linked below). 

Instructions for downloading MR and PET scan files: [Instructions to download MR or PET scan files](https://github.com/NrgXnat/oasis-scripts#downloading-mr-and-pet-scan-files)
Here is a link to an example of what your scan sessions CSV file should look like if you want to download scans: [download_scans/oasis_scan_download_example.csv](https://github.com/NrgXnat/oasis-scripts/blob/master/download_scans/oasis_scan_download_example.csv)

Instructions for downloading Freesurfer output files: [Instructions to download Freesurfer files](https://github.com/NrgXnat/oasis-scripts#downloading-freesurfer-files)
Here is a link to an example of what your Freesurfer CSV file should look like for downloading Freesurfer output files: [download_freesurfer/fs_download_example.csv](https://github.com/NrgXnat/oasis-scripts/blob/master/download_freesurfer/fs_download_example.csv)

Instructions for downloading PUP output files: [Instructions to download PUP files](https://github.com/NrgXnat/oasis-scripts#download_pupdownload_oasis_pupsh)
Here is a link to an example of what your PUP CSV file should look like for downloading PUP output files: [download_pup/pup_download_example.csv](https://github.com/NrgXnat/oasis-scripts/blob/master/download_pup/pup_download_example.csv)

I'm going to close this issue since it is not related to a bug in the script functionality. If you have further questions about how to use the scripts you can use the contact form on [oasis-brains.org](https://www.oasis-brains.org).
