### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Mda233** [NrgXnat/oasis-scripts#24]
Hi,
First, I want to thank you for providing the downloading script.
I have the following issue when I run the script. It looks like the URL for downloading has been changed.
Could you please help me verify if the URL in the script is still working?
I really appreciate it!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
--2022-07-12 16:40:05--  https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d3132%0D/scans/ALL/files?format=tar.gz
Resolving central.xnat.org (central.xnat.org)... 128.252.217.126
Connecting to central.xnat.org (central.xnat.org)|128.252.217.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-12 16:40:05 ERROR 404: Not Found.

.ould not download all scans for OAS30001_MR_d3132
.one with OAS30001_MR_d3132
.ownloading all scans for OAS30002_MR_d0371

**Comment by sarahkeefe** [comment]
Hi, based on the URL generated (that has the %0D character added after the experiment label), it looks like you didn’t correctly follow the convert to Unix step on your CSV. Revisit the section in the instructions that describes how to convert your CSV file to Unix format and retry. 

If you still see a 404 with a corrected CSV and URL then that is likely due to a typo in your login info. The URL should give a result if you log in to XNAT Central and then access the URL.
