### ISSUE TITLE
problem download oasis3

### ISSUE THREAD

**Issue by mxia96** [NrgXnat/oasis-scripts#28]
Dear expert:
I have a problem like this:
Could not get Freesurfer OAS30001_Freesurfer53_d4467 in OAS30001_MR_d4467.
Checking for Freesurfer ID OAS30002_Freesurfer50_d0371 associated with OAS30002_MR_d0371.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
149   298  149   298    0     0    625      0 --:--:-- --:--:-- --:--:--  1544
This is my csv file.
Could you help me figure out this problem?
Thanks
[freesurfer.csv](https://github.com/NrgXnat/oasis-scripts/files/10106394/freesurfer.csv)

**Comment by sarahkeefe** [comment]
Hi,
This can happen if you aren't authorized to access the data or haven't entered your login credentials correctly. Are you able to log in on central.xnat.org with the same account details (username and password) you are using with the script? If you had an approved data request and received an invite to the "OASIS3" project and can access the "OASIS3" project on XNAT Central then you should be able to access the data.
If you have access, let me know the full command you are using, and what command you used to convert to Unix format.

**Comment by mxia96** [comment]
> 
Thank you for replying. This is my code.
'/ifs/loni/faculty/shi/spectrum/mxia/code/Oasis/oasis-scripts-master/download_freesurfer/download_oasis_freesurfer.sh /ifs/loni/faculty/shi/spectrum/mxia/code/Oasis/freesurfer.csv /ifs/loni/faculty/shi/spectrum/mxia/datas/Oasis/oasis3/Freesurfer xiamingy'
and this is my code for converting 'dos2unix freesurfer.csv'
Thank you

**Comment by sarahkeefe** [comment]
Are you able to download a zip file via your web browser when you log in to XNAT Central and follow this link?

https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d0129/assessors/OAS30001_Freesurfer53_d0129/files?format=zip

If so, try rerunning the script make sure you correctly enter your XNAT Central password. 

You can also try using a login token by logging in to XNAT Central and then going to this URL:
https://central.xnat.org/data/services/tokens/issue
and copy and paste the string next to "alias" as your username (as input when running the script instead of your XNAT username, but don't include the quotation marks)
And then when it asks for password, paste in the string for "secret" (again without the quotation marks).

Here is an example of the token:

![image](https://user-images.githubusercontent.com/264991/204380215-020ff26b-167f-48a8-8d16-283614c132f8.png)

When you are logged in your username will be in blue instead of "guest".
You would copy the yellow string and use that as input to the script, instead of "xiamingy"
Then you would run the script, and when it asks for your password,  you would paste in the orange string and press enter.

**Comment by mxia96** [comment]
Thank you, it works now!
Really appreciate it
