### ISSUE TITLE
TASK_NAME_MUST_DEFINE BIDS error for OASIS3

### ISSUE THREAD

**Issue by clarkenj** [NrgXnat/oasis-scripts#31]
When running the BIDS validator I get the following error for multiple files:

```
[ERR] You have to define 'TaskName' for this file. (code: 50 - TASK_NAME_MUST_DEFINE)^[[39m
./sub-OAS30001/ses-d0129/func/sub-OAS30001_ses-d0129_task-rest_run-01_bold.nii.gz
```
I believe that `“Task name” :“rest"` must be added to the corresponding json files (e.g.` sub-OAS30001_ses-d0129_task-rest_run-01_bold.json`). I can do this but not sure if it's a common error and something you would want to add to the downloadable data.

**Comment by sarahkeefe** [comment]
Ah ok, so it's expecting a new line for TaskName in the JSON files to validate? Sorry about that! 
Is there a way for your BIDS validator to use an earlier version/specification of BIDS? That might solve it since we did the original BIDS conversion in 2017 using the current BIDS specification at the time, which has shifted over the years. 

We used dcm2niix 2017-October-17 for file conversion and for generating the BIDS JSONs so the TaskName may not have been automatically added in JSONs generated by that version of dcm2niix. It's probably missing from all the BOLD JSON files - if you need the files to validate you should probably go ahead and add it to the files you need yourself since we most likely won't have the resources to update that in the whole dataset. But I'll leave this issue open while I look into whether we will be able to make this update.

**Comment by clarkenj** [comment]
Yes I believe so. No problem! Ah OK, I will try with an earlier version (there are also some other errors I am working through, so that might solve them!) but add myself if needed. Thank you for your help
