### ISSUE TITLE
Checking expected behaviour of download_oasis_scans_bids.sh

### ISSUE THREAD

**Issue by clarkenj** [NrgXnat/oasis-scripts#32]
Hi again, I think I might be getting the BIDS errors because the dataset hasn't downloaded properly. I have all of the subject directories but also the subject `.tar.gz` files still (which I assume I don't need?). I could delete them/ add to a `.bidsignore` file but I wonder if the script has not finished running. Also there is a `OASIS3_data_files.tar.gz` but nothing for `OASIS_cohort_files`, although it's listed in the csv for download. Is this expected behaviour of the `download_oasis_scans_bids.sh` script? Thanks so much!

**Comment by sarahkeefe** [comment]
I just checked the download_oasis_scans_bids.sh script and the line where the original .tar.gz files are supposed to be removed got commented out - big oops on my end! Just fixed it in the BIDS download file for future users. 

In the scripts the tar.gz files are supposed to be downloaded, extracted, and then deleted once the files get extracted. If you have the scan files themselves (the contents of the .tar.gz files, NIFTI plus JSON files for each scan) in the expected locations in addition to the .tar.gzs then the .tar.gzs are extra and you can definitely delete them or `.bidsignore` them - you wouldn't be removing data from your downloaded dataset, just the zipped files that were originally downloaded. 
 
The OASIS3_data_files.tar.gz and any general "OASIS files" things are relatively newly added to OASIS - those are fake "subjects" that just contain files with the full spreadsheets of data but no scan files that should be validated with a BIDS validator. Those unusually-named subjects should probably be removed from any folder you are running BIDS validations on and stored totally separately, or maybe adding to a `.bidsignore` file would work, since they 100% won't validate. I should update the readme to incorporate that information - I will try to get to that soon!

**Comment by clarkenj** [comment]
Ok this is super helpful, thank you so much! Should there be a `participants.tsv` file downloaded?

**Comment by sarahkeefe** [comment]
No, we didn't include participants.tsv files as part of the BIDS specification version we used for OASIS3 and OASIS4.

**Comment by sarahkeefe** [comment]
Ok, I also updated the readme to add in the details on the "0AS_data_files" subject entries - hope that is helpful! Going to close this up now, feel free to reopen or open another issue if you run into more questions!
