### ISSUE TITLE
Downloading oasis3_tau pet data

### ISSUE THREAD

**Issue by iamnielsjanssen** [NrgXnat/oasis-scripts#33]
Hi I am having a problem downloading the oasis3_tau PET data. I am using ubuntu 18.04 with the following command:
./download_oasis_scans.sh test.csv /ImageData/DataSets/OASIS3_TAU $username
where test.csv contains two lines:
OAS30001_MR_d3746
OAS30001_AV1451_d3746

The first line downloads without problems, the second line fails to download. Not sure I understand why. 

Thanks for any help.

**Comment by sarahkeefe** [comment]
I think at the time this issue was opened I hadn't updated the download scripts to incorporate the OASIS4, OASIS3_AV1451, or OASIS3_AV1451L projects. I updated the scan download scripts since this was posted. 

Now by default the updated scan download script can handle a mix of OASIS4, OASIS4_AV1451, or OASIS3 IDs and identifies which project to download from based on the first letters of the ID. (This is admittedly not a seamless solution but is to save the effort of having users need to specify which project to download from). 

The only issue is if you are downloading a mix of data from the OASIS3_AV1451 and OASIS3_AV1451L projects (tau and longitudinal tau projects). By default the scripts will attempt to download any scan sessions that start with "OAS3" and contain "AV1451" from the OASIS3_AV1451 project (not the longitudinal tau project OASIS3_AV1451L). If you need to download data from the longitudinal tau project, you'll need to:
- Run the download script first with only your non-longitudinal tau sessions. 
- Then create a separate session list that contains only the session labels from OASIS3_AV1451L (and none from OASIS3_AV1451). 
- Then modify the scan download script to [uncomment line 142](https://github.com/NrgXnat/oasis-scripts/blob/master/download_scans/download_oasis_scans.sh#L142v). Save the script.
- Convert the script and your updated input file to Unix format with `dos2unix`.

Then you should be able to run the modified scan download script and any sessions that start with OAS3 and contain AV1451 will be pulled from the OASIS3_AV1451L longitudinal project instead.

I'm going to close this issue but feel free to reopen it if you have further issues with this topic.
