### ISSUE TITLE
Unable to download images from NITRC

### ISSUE THREAD

**Issue by ahzhu** [NrgXnat/oasis-scripts#43]
We've been trying to download OASIS4 data from NITRC using the scripts provided in this repo but have been unsuccessful. 

Using `download_oasis_scans.sh`, we get the following output.

> Downloading all scans for OAS42000_MR_d3016.
> https://nitrc.org/ir/data/archive/projects/OASIS4/subjects/OAS42000/experiments/OAS42000_MR_d3016/scans/ALL/files?format=tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   298  100   298    0     0   1221      0 --:--:-- --:--:-- --:--:--  1226
> Could not complete the scan download. Either could not find any scans for OAS42000_MR_d3016, or the download failed.
> Done with OAS42000_MR_d3016.

Switching to `download_oasis_scans_wget.sh`, we still can't connect.

> Downloading all scans for OAS42000_MR_d3016.
> --2024-06-19 12:58:32--  https://nitrc.org/ir/data/archive/projects/OASIS4/subjects/OAS42000/experiments/OAS42000_MR_d3016/scans/ALL/files?format=tar.gz
> Resolving nitrc.org (nitrc.org)... 52.3.190.103
> Connecting to nitrc.org (nitrc.org)|52.3.190.103|:443... connected.
> HTTP request sent, awaiting response... 401 Unauthorized
> Unknown authentication scheme.
> Authorization failed.
> Could not download all scans for OAS42000_MR_d3016.
> Done with OAS42000_MR_d3016.

We are able to log into NITRC and have permission to access other data such as the OASIS4 spreadsheets. Any help would be greatly appreciated!

**Comment by sarahkeefe** [comment]
Hi, sorry for the delay! Looks like something in the NITRC URL changed the way downloads work. I updated the download scripts to reflect the change and I suspect this will solve it - try out the updated scripts and let me know if you still run into the same issue.

**Comment by ahzhu** [comment]
Hi, Sarah. Thanks for the response! I tried the updated scripts, but unfortunately I still get the same error. 

Output from `download_oasis_scans.sh`:

> Downloading all scans for OAS42000_MR_d3016.
> https://www.nitrc.org/ir/data/archive/projects/OASIS4/subjects/OAS42000/experiments/OAS42000_MR_d3016/scans/ALL/files?format=zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   298  100   298    0     0    675      0 --:--:-- --:--:-- --:--:--   674
> Could not download all scans for OAS42000_MR_d3016.
> Done with OAS42000_MR_d3016.

**Comment by sarahkeefe** [comment]
Hmm, are you able to log in to NITRC with the same credentials you're using for the script, and then paste that URL in your browser? Let me know if that gives you an error.

**Comment by ahzhu** [comment]
I've logged into the NITRC website, but when I try accessing the zip URL, I get the following error. 

> Unable to identify subject
> 
> You can get technical details [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5).
> Please continue your visit at our [home page](https://www.nitrc.org/).

I also tried to download the images via the XNAT Desktop Client (XML set up through NITRC), but it just hangs in a "Queued" state.

**Comment by sarahkeefe** [comment]
Ok, 2 potential things: 
- Does the in-browser URL you’re using start with “https://nitrc.org” or “https://www.nitrc.org”? That’s something that seemed to make a difference when I was testing and running into the same issue - for some reason the “https://www” seemed to be needed. 
- Are you able to view and access the OASIS4 project on the NITRC website, and click through to find that subject/scan session page?

**Comment by ahzhu** [comment]
- The URL does indeed have the "www" prefix. I used [this URL](https://www.nitrc.org/ir/data/archive/projects/OASIS4/subjects/OAS42000/experiments/OAS42000_MR_d3016/scans/ALL/files?format=zip).
- In NITRC, if I click through to a specific subject/scan session/scan (e.g., MR Session: OAS42000_MR_d3016 - anat1 - FLAIR), then I'm able to download individual scans

**Comment by sarahkeefe** [comment]
Yep, that’s what I meant. Ok, I’m out of ideas, I suspect that there may have been a configuration change on the NITRC side of things. I’ll try to get in touch with them to see if they have any insight. So sorry for the trouble!

**Comment by ahzhu** [comment]
That's all right. Thanks for looking into this!

**Comment by sarahkeefe** [comment]
Hi again, sorry for the delay. 

I just tried a download attempt and had success with the same sessions/URLs you were using. There's a small chance that something changed and yours may work now as well, so it could be worth trying again. 

If not, I recommend contacting the NITRC administrators since it seems to be an issue on their end, either server- or access-related: [https://www.nitrc.org/help/contact_us.php](https://www.nitrc.org/help/contact_us.php). One thing they might be able to try is the "clear user access cache" feature of XNAT that might help you with the OASIS4 data. They might find it helpful if you send them a link to this Github issue as well so they can know what you've tried and what errors you're seeing.

You might also want to try an example download of OASIS3 data (if you have access to that project as well) to see if one project works for you and another doesn't. Then you can let them know what's going on and they can possibly troubleshoot the project settings. Unfortunately since OASIS has moved to NITRC I no longer have administrative access to troubleshoot user accounts and settings so I think they'll be the best equipped to help you further since it seems to be something like that.

I'm going to close this issue, but feel free to re-open or open a new one if you come across something else script-related. Sorry this isn't a very helpful issue conclusion.

**Comment by RDoerfel** [comment]
Hi,
I am experiencing a similar error. I'm on Linux, and I used 'dos2unix' to save the edited CSV file with UTF-8 encoding. Here are some example lines:

OAS30001_MR_d0129
OAS30001_MR_d0757

Now I try to run the following command:

`download_oasis_scans_bids.sh rdoerfel_2_4_2025_7_48_21_cleaned.csv /indirect/proc_data1/brainage/OASIS/OASIS3/raw rdoerfel`
After providing my password, I double-checked that my username and password were correct by logging in to [www.nitrc.org](http://www.nitrc.org/). I have a user and access to OASIS3.

Now I get the following error:

> Downloading all scans for OAS30004_MR_d4700.
> https://www.nitrc.org/ir/data/archive/projects/OASIS3/subjects/OAS30004/experiments/OAS30004_MR_d4700/scans/ALL/files?format=tar.gz
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> Dload  Upload   Total   Spent    Left  Speed
> 100   298  100   298    0     0    894      0 --:--:-- --:--:-- --:--:--   897
> Could not complete the scan download. Either could not find any scans for OAS30004_MR_d4700, or the download failed.
> Done with OAS30004_MR_d4700.

When I instead try to run
`download_oasis_scans.sh rdoerfel_2_4_2025_7_48_21_cleaned.csv /indirect/proc_data1/brainage/OASIS/OASIS3/raw rdoerfel`

I get the following error:

> Enter your password for accessing OASIS data on NITRC IR:
> Error starting session.  Maybe a bad username/password?

Which is odd, because I just explicitly logged into NITRC with exactly those credentials. Following up on this, I provided download_oasis_scans_bids.sh with a random number as password, to see how it behaves if it fails. Turns out, I get the same error as when giving the correct password, namely:

> Downloading all scans for OAS30004_MR_d4700.
> https://www.nitrc.org/ir/data/archive/projects/OASIS3/subjects/OAS30004/experiments/OAS30004_MR_d4700/scans/ALL/files?format=tar.gz
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> Dload  Upload   Total   Spent    Left  Speed
> 100   298  100   298    0     0    894      0 --:--:-- --:--:-- --:--:--   897
> Could not complete the scan download. Either could not find any scans for OAS30004_MR_d4700, or the download failed.
> Done with OAS30004_MR_d4700.

So maybe it has something to do with the login?

Best regards,
Ruben.
